# Generated by Django 4.2.4 on 2023-08-21 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent", models.EmailField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("zipcode", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                ("bedrooms", models.IntegerField()),
                ("bathrooms", models.IntegerField()),
                (
                    "sale_type",
                    models.CharField(
                        choices=[("For Sale", "For Sale"), ("For Rent", "For Rent")],
                        default="For Sale",
                        max_length=10,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("House", "House"),
                            ("Apartment", "Apartment"),
                            ("Land", "Land"),
                        ],
                        default="House",
                        max_length=10,
                    ),
                ),
                ("main_photo", models.ImageField(upload_to="property_service/")),
                ("photo_1", models.ImageField(upload_to="property_service/")),
                ("photo_2", models.ImageField(upload_to="property_service/")),
                ("photo_3", models.ImageField(upload_to="property_service/")),
                ("is_published", models.BooleanField(default=False)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
